pname: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install gh package
      run: npm install -g gh

    - name: Build
      run: |
        npm install
        grunt
            
    - name: Deploy to IBM Cloud Foundry
  # You may pin to the exact commit or the version.
  # uses: IBM/cloudfoundry-deploy@fcb5a74cb36e7cd0bfe9f9b5d9d57aab85d00bd1
  uses: IBM/cloudfoundry-deploy@v2.1
  with:
    # IBM Cloud API key
    IBM_CLOUD_API_KEY: 
    # IBM Cloud Foundry API endpoint
    IBM_CLOUD_CF_API: 
    # IBM Cloud Foundry organization name
    IBM_CLOUD_CF_ORG: 
    # IBM Cloud Foundry space name
    IBM_CLOUD_CF_SPACE: 
    # App Manifest file
    APP_MANIFEST_FILE: # optional, default is manifest.yml
    # App variables file
    APP_VARS_FILE: # optional
    # IBM Cloud Foundry resource group
    RESOURCE_GROUP: # optional
          
